services:
  - type: web
    name: flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:8080 --workers 2 --timeout 120
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://recon:wDydgBlqUNrjrVDr@cluster0.h4ntq3p.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0